# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://vigeomarine.com
title: Vigeo Marine
email: sales@vigeoconstruction.com
author: Joshua Coffie
description:
  Vigeo Marine - When it absolutely has to be done right.
copyright: 'Copyright &copy; 2021 Vigeo Corporation. All Rights Reserved.'
credits: 'Vigeo Marine is a subsidiary of <a href="http://vigeocorp.com">Vigeo Corp</a>, 2021.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:
  - title: github
    url:
  - title: linkedin
    url:

# Google Analytics
google_analytics: UA-162088172-1
