# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://vigeocorp.com
title: Vigeo Protect
email: sales@vigeoconstruction.com
author: Joshua Coffie
description:
  Vigeo Protect - Protecting your freedom and assets.
copyright: 'Copyright &copy; 2020 Vigeo Corporation. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:
  - title: github
    url:
  - title: linkedin
    url:

# Google Analytics
google_analytics: UA-162088172-1
